/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import AgendaAlumnosCursos.Ficheros;
import AgendaAlumnosCursos.GestionAlumnos;

/**
 *
 * @author Iker Ruiz
 */
public class PanelListadoAlumnos extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrabAlumnos
     */
    public PanelListadoAlumnos(GestionAlumnos gesAlu) {
        initComponents();
        this.gesAlu = gesAlu;
        refrescar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrabajo = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        eticTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btBuscar = new javax.swing.JPanel();
        textBtEntrar = new javax.swing.JLabel();
        eticGener = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelListado = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(970, 669));
        setPreferredSize(new java.awt.Dimension(970, 669));

        panelTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        panelTrabajo.setPreferredSize(new java.awt.Dimension(0, 589));

        panelTitulo.setBackground(new java.awt.Color(255, 255, 255));

        eticTitulo.setBackground(new java.awt.Color(255, 255, 255));
        eticTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        eticTitulo.setForeground(new java.awt.Color(51, 51, 51));
        eticTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eticTitulo.setText("LISTADO DE ALUMNOS");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eticTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(eticTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btBuscar.setBackground(new java.awt.Color(78, 156, 204));

        textBtEntrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtEntrar.setForeground(new java.awt.Color(255, 255, 255));
        textBtEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtEntrar.setText("Generar");
        textBtEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btBuscarLayout = new javax.swing.GroupLayout(btBuscar);
        btBuscar.setLayout(btBuscarLayout);
        btBuscarLayout.setHorizontalGroup(
            btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
            .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        btBuscarLayout.setVerticalGroup(
            btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(btBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        eticGener.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        eticGener.setText("Generar documento");

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        panelListado.setBackground(new java.awt.Color(204, 204, 204));
        panelListado.setColumns(20);
        panelListado.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        panelListado.setRows(5);
        jScrollPane2.setViewportView(panelListado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eticGener, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eticGener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que refresca cada vez que se abre la clase, la lista de alumnos
     * existentes en la base de datos
     */
    public void refrescar() {
        ArrayList<String> lista = new ArrayList();
        lista = gesAlu.mostrarTodo();
        int i=0;
        
        for (String e : lista) {
            panelListado.append("Alumno "+i+"\t"+e+"\n");            
            i++;

        }

    }
    private void textBtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtEntrarMouseClicked
        Ficheros fichero = new Ficheros();
        fichero.escribir(panelListado.getText(), "listadoAlumnos.txt");
         javax.swing.JOptionPane.showMessageDialog(this, "Fichero Generado con Exito", "GUARDAR FICHERO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_textBtEntrarMouseClicked

    /**
     * Metodo que guarda a modo de fichero de texto, la lista de alumnos expuesta
     * por el metodo refrescar
     * @param evt 
     */
    private void textBtEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtEntrarMouseEntered
        btBuscar.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtEntrarMouseEntered

    private void textBtEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtEntrarMouseExited
        btBuscar.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtEntrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btBuscar;
    private javax.swing.JLabel eticGener;
    private javax.swing.JLabel eticTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea panelListado;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JLabel textBtEntrar;
    // End of variables declaration//GEN-END:variables
    private GestionAlumnos gesAlu;
}
