/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import javax.swing.JOptionPane;
import AgendaAlumnosCursos.GestionInscripciones;
import AgendaAlumnosCursos.MisExceptions;
import AgendaAlumnosCursos.Verificaciones;

/**
 *
 * @author Iker Ruiz
 */
public class PanelMatricular extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrabAlumnos
     */
    public PanelMatricular(GestionInscripciones gesInsc) {
        initComponents();
        this.gesInsc = gesInsc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrabajo = new javax.swing.JPanel();
        eticAlumno = new javax.swing.JLabel();
        cajaTelAlu = new javax.swing.JTextField();
        eticCurso = new javax.swing.JLabel();
        cajaNombreCurso = new javax.swing.JTextField();
        btMat = new javax.swing.JPanel();
        textBtMat = new javax.swing.JLabel();
        btDesMat = new javax.swing.JPanel();
        textBtDesMat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btCalif = new javax.swing.JPanel();
        textBtCalif = new javax.swing.JLabel();
        cajaCalif = new javax.swing.JTextField();
        eticCalif = new javax.swing.JLabel();

        panelTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        panelTrabajo.setPreferredSize(new java.awt.Dimension(0, 589));

        eticAlumno.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        eticAlumno.setForeground(new java.awt.Color(51, 51, 51));
        eticAlumno.setText("Telefono Alumno");

        cajaTelAlu.setBackground(new java.awt.Color(204, 204, 204));
        cajaTelAlu.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cajaTelAlu.setForeground(new java.awt.Color(51, 51, 51));
        cajaTelAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelAluActionPerformed(evt);
            }
        });

        eticCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        eticCurso.setForeground(new java.awt.Color(51, 51, 51));
        eticCurso.setText("Nombre Curso");

        cajaNombreCurso.setBackground(new java.awt.Color(204, 204, 204));
        cajaNombreCurso.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cajaNombreCurso.setForeground(new java.awt.Color(51, 51, 51));
        cajaNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreCursoActionPerformed(evt);
            }
        });

        btMat.setBackground(new java.awt.Color(78, 156, 204));

        textBtMat.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtMat.setForeground(new java.awt.Color(255, 255, 255));
        textBtMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtMat.setText("Matricula");
        textBtMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtMatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btMatLayout = new javax.swing.GroupLayout(btMat);
        btMat.setLayout(btMatLayout);
        btMatLayout.setHorizontalGroup(
            btMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(btMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtMat, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        btMatLayout.setVerticalGroup(
            btMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(btMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtMat, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        btDesMat.setBackground(new java.awt.Color(78, 156, 204));

        textBtDesMat.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtDesMat.setForeground(new java.awt.Color(255, 255, 255));
        textBtDesMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtDesMat.setText("Desmatricular");
        textBtDesMat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtDesMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtDesMatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtDesMatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtDesMatMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btDesMatLayout = new javax.swing.GroupLayout(btDesMat);
        btDesMat.setLayout(btDesMatLayout);
        btDesMatLayout.setHorizontalGroup(
            btDesMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(btDesMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtDesMat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
        );
        btDesMatLayout.setVerticalGroup(
            btDesMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
            .addGroup(btDesMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtDesMat, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(180, 253, 252));

        btCalif.setBackground(new java.awt.Color(78, 156, 204));

        textBtCalif.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtCalif.setForeground(new java.awt.Color(255, 255, 255));
        textBtCalif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtCalif.setText("Calificar");
        textBtCalif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtCalif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtCalifMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtCalifMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtCalifMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btCalifLayout = new javax.swing.GroupLayout(btCalif);
        btCalif.setLayout(btCalifLayout);
        btCalifLayout.setHorizontalGroup(
            btCalifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(btCalifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtCalif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
        );
        btCalifLayout.setVerticalGroup(
            btCalifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(btCalifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtCalif, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        cajaCalif.setBackground(new java.awt.Color(204, 204, 204));
        cajaCalif.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cajaCalif.setForeground(new java.awt.Color(51, 51, 51));
        cajaCalif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCalifActionPerformed(evt);
            }
        });

        eticCalif.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        eticCalif.setForeground(new java.awt.Color(51, 51, 51));
        eticCalif.setText("Nota del Alumno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eticCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(eticCalif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrabajoLayout.createSequentialGroup()
                        .addComponent(eticAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(807, 946, Short.MAX_VALUE))
                    .addGroup(panelTrabajoLayout.createSequentialGroup()
                        .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaTelAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eticCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTrabajoLayout.createSequentialGroup()
                                .addComponent(btMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addComponent(btDesMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(eticAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTrabajoLayout.createSequentialGroup()
                        .addComponent(cajaTelAlu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(eticCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDesMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cajaTelAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelAluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTelAluActionPerformed

    private void cajaNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreCursoActionPerformed

    /**
     * metodo para cuando clicamos recoge los datos que hay en las cajas las
     * compruba y pasa los datos a gestion de Inscripciones para mataricular a
     * un alumno
     *
     * @param evt
     */
    private void textBtMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtMatMouseClicked
        String telAlumno = cajaTelAlu.getText().trim();
        String nomCurso = cajaNombreCurso.getText().trim();
        try {
            verif.hayAlgo(telAlumno);
            verif.soloNum(telAlumno);
            verif.nuveCaracteres(telAlumno);
            verif.hayAlgo(nomCurso);
            verif.tieneComa(telAlumno);
            verif.tieneComa(nomCurso);
            gesInsc.MatricularAlumnos(telAlumno, nomCurso);
            cajaTelAlu.setText("");
            cajaNombreCurso.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Matriculado con exito", "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (MisExceptions me) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_textBtMatMouseClicked

    /**
     * metodo para cambiar de color cuando pasamos por encima con el raton el
     * boton de matricular
     *
     * @param evt
     */
    private void textBtMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtMatMouseEntered
        btMat.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtMatMouseEntered

    /**
     * metodo para cambiar de color cuando pasamos por encima con el raton el
     * boton de matricular
     *
     * @param evt
     */
    private void textBtMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtMatMouseExited
        btMat.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtMatMouseExited

    /**
     * metodo para cuando clicamos recoge los datos que hay en las cajas las
     * compruba y pasa los datos a gestion de inscripciones para desmatricular
     *
     * @param evt
     */
    private void textBtDesMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtDesMatMouseClicked
        String telAlumno = cajaTelAlu.getText().trim();
        String nomCurso = cajaNombreCurso.getText().trim();
        int n = JOptionPane.showConfirmDialog(
                this,
                "¿Estas seguro de querer desmatricular al alumno?",
                "Alumno desmatriculado",
                JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.OK_OPTION) {

            try {
                verif.hayAlgo(telAlumno);
                verif.soloNum(telAlumno);
                verif.nuveCaracteres(telAlumno);
                verif.hayAlgo(nomCurso);
                verif.tieneComa(telAlumno);
                verif.tieneComa(nomCurso);
                gesInsc.Desmatricular(telAlumno, nomCurso);
                cajaTelAlu.setText("");
                cajaNombreCurso.setText("");
                javax.swing.JOptionPane.showMessageDialog(this, "Desmatriculado con exito", "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (MisExceptions me) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            }
        }
    }//GEN-LAST:event_textBtDesMatMouseClicked

    private void textBtDesMatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtDesMatMouseEntered
        btDesMat.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtDesMatMouseEntered

    private void textBtDesMatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtDesMatMouseExited
        btDesMat.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtDesMatMouseExited

    /**
     * metodo para cuando clicamos recoge los datos que hay en las cajas las
     * compruba y pasa los datos a gestion de inscripciones para calificar
     *
     * @param evt
     */
    private void textBtCalifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtCalifMouseClicked
        String telAlumno = cajaTelAlu.getText().trim();
        String nomCurso = cajaNombreCurso.getText().trim();
        String calilf = cajaCalif.getText().trim();
        try {
            float num = verif.esFloat(calilf);
            verif.hayAlgo(telAlumno);
            verif.soloNum(telAlumno);
            verif.nuveCaracteres(telAlumno);
            verif.hayAlgo(nomCurso);
            verif.tieneComa(telAlumno);
            verif.tieneComa(nomCurso);
            if (num >= 0) {
                gesInsc.CalificarAlumno(telAlumno, nomCurso, num);
                cajaTelAlu.setText("");
                cajaNombreCurso.setText("");
                cajaCalif.setText("");
                javax.swing.JOptionPane.showMessageDialog(this, "Calificado con exito", "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se puede calificar con negativos", "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (MisExceptions me) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "MATRICULAR", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_textBtCalifMouseClicked

    private void textBtCalifMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtCalifMouseEntered
        btCalif.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtCalifMouseEntered

    private void textBtCalifMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtCalifMouseExited
        btCalif.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtCalifMouseExited

    private void cajaCalifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCalifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCalifActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btCalif;
    private javax.swing.JPanel btDesMat;
    private javax.swing.JPanel btMat;
    private javax.swing.JTextField cajaCalif;
    private javax.swing.JTextField cajaNombreCurso;
    private javax.swing.JTextField cajaTelAlu;
    private javax.swing.JLabel eticAlumno;
    private javax.swing.JLabel eticCalif;
    private javax.swing.JLabel eticCurso;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JLabel textBtCalif;
    private javax.swing.JLabel textBtDesMat;
    private javax.swing.JLabel textBtMat;
    // End of variables declaration//GEN-END:variables
    private GestionInscripciones gesInsc;
    Verificaciones verif = new Verificaciones();
}
