/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import AgendaAlumnosCursos.GestionAlumnos;
import AgendaAlumnosCursos.MisExceptions;
import AgendaAlumnosCursos.Verificaciones;

/**
 *
 * @author Iker Ruiz
 */
public class PanelGestionAlumno extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrabAlumnos
     */
    public PanelGestionAlumno(GestionAlumnos gesAlu) {
        initComponents();
        this.gesAlu = gesAlu;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrabajo = new javax.swing.JPanel();
        cajaBusqueda = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JPanel();
        textBtBuscar = new javax.swing.JLabel();
        etqNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etqApellido = new javax.swing.JLabel();
        textoApellido = new javax.swing.JTextField();
        etqDireccion = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        etqTelefono = new javax.swing.JLabel();
        btBorrar = new javax.swing.JPanel();
        textBtBorrar = new javax.swing.JLabel();
        btModificar = new javax.swing.JPanel();
        textBtModificar = new javax.swing.JLabel();
        listadoAlumnos = new javax.swing.JScrollPane();
        pLista = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(970, 669));
        setPreferredSize(new java.awt.Dimension(970, 669));

        panelTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        panelTrabajo.setPreferredSize(new java.awt.Dimension(0, 589));

        cajaBusqueda.setBackground(new java.awt.Color(204, 204, 204));
        cajaBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        cajaBusqueda.setText("Introduce el nombre del Alumno");
        cajaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaBusquedaMousePressed(evt);
            }
        });

        botonBuscar.setBackground(new java.awt.Color(78, 156, 204));

        textBtBuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        textBtBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtBuscar.setText("Buscar");
        textBtBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonBuscarLayout = new javax.swing.GroupLayout(botonBuscar);
        botonBuscar.setLayout(botonBuscarLayout);
        botonBuscarLayout.setHorizontalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textBtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        botonBuscarLayout.setVerticalGroup(
            botonBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textBtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        etqNombre.setBackground(new java.awt.Color(51, 51, 51));
        etqNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqNombre.setForeground(new java.awt.Color(51, 51, 51));
        etqNombre.setText("Nombre");

        textoNombre.setBackground(new java.awt.Color(204, 204, 204));
        textoNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(51, 51, 51));

        etqApellido.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqApellido.setForeground(new java.awt.Color(51, 51, 51));
        etqApellido.setText("Apellido");

        textoApellido.setBackground(new java.awt.Color(204, 204, 204));
        textoApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoApellido.setForeground(new java.awt.Color(51, 51, 51));

        etqDireccion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqDireccion.setForeground(new java.awt.Color(51, 51, 51));
        etqDireccion.setText("Direccion ");

        textoDireccion.setBackground(new java.awt.Color(204, 204, 204));
        textoDireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoDireccion.setForeground(new java.awt.Color(51, 51, 51));

        textoTelefono.setBackground(new java.awt.Color(204, 204, 204));
        textoTelefono.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoTelefono.setForeground(new java.awt.Color(51, 51, 51));

        etqTelefono.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqTelefono.setForeground(new java.awt.Color(51, 51, 51));
        etqTelefono.setText("Telefono");

        btBorrar.setBackground(new java.awt.Color(78, 156, 204));

        textBtBorrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtBorrar.setForeground(new java.awt.Color(255, 255, 255));
        textBtBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtBorrar.setText("Borrar");
        textBtBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtBorrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtBorrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btBorrarLayout = new javax.swing.GroupLayout(btBorrar);
        btBorrar.setLayout(btBorrarLayout);
        btBorrarLayout.setHorizontalGroup(
            btBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
            .addGroup(btBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );
        btBorrarLayout.setVerticalGroup(
            btBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(btBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        btModificar.setBackground(new java.awt.Color(78, 156, 204));

        textBtModificar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtModificar.setForeground(new java.awt.Color(255, 255, 255));
        textBtModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtModificar.setText("Modificar");
        textBtModificar.setToolTipText("");
        textBtModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtModificarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btModificarLayout = new javax.swing.GroupLayout(btModificar);
        btModificar.setLayout(btModificarLayout);
        btModificarLayout.setHorizontalGroup(
            btModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(btModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        btModificarLayout.setVerticalGroup(
            btModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(btModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(textBtModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        pLista.setBackground(new java.awt.Color(204, 204, 204));
        pLista.setForeground(new java.awt.Color(51, 51, 51));
        pLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pListaMouseClicked(evt);
            }
        });
        listadoAlumnos.setViewportView(pLista);

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTrabajoLayout.createSequentialGroup()
                        .addComponent(cajaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTrabajoLayout.createSequentialGroup()
                        .addComponent(listadoAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etqNombre)
                                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etqApellido)
                                .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etqDireccion)
                                .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etqTelefono)
                                .addComponent(btModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajaBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTrabajoLayout.createSequentialGroup()
                        .addComponent(etqNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(etqApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(etqDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(etqTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(listadoAlumnos))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para refrecar la panel del listado con el listado que le pasamos por parametro
     * @param lista
     */
    public void refrescar(ArrayList<String> lista) {
        DefaultListModel<String> dlm = new DefaultListModel();
        try {
            for (int i = 0; i < lista.size(); i++) {
                dlm.add(i, lista.get(i));
            }
        } catch (Exception e) {
        }
        this.pLista.setModel(dlm);
    }
    
    /**
     * Metodo para cuando clicamos en el panel de buscar para realizar la busqueda del texto que se en cuentra en la caja de 
     * busqueda
     * @param evt
     */
    private void textBtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtBuscarMouseClicked
        String nomBusqueda = cajaBusqueda.getText().trim();
        ArrayList<String> lista = new ArrayList();
        try {
            verif.hayAlgo(nomBusqueda);
            verif.tieneComa(nomBusqueda);
            ResultSet resultado = gesAlu.buscar(nomBusqueda, "");
            while (resultado.next()) {//recorre todas las filas de la consulta
                lista.add(resultado.getString("nombre") + ", " + resultado.getString("apellido") + ", " + resultado.getString("telefono"));//lo muestra lo que pongas aqui
            }
        } catch (SQLException ex) {
//            ex.printStackTrace();

        } catch (MisExceptions me) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "BUSQUEDA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        refrescar(lista);

    }//GEN-LAST:event_textBtBuscarMouseClicked

    /**
     * Metodo para cuando entra el raton en el panel de Buscar
     * @param evt
     */
    private void textBtBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtBuscarMouseEntered
        botonBuscar.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtBuscarMouseEntered

    /**
     * Metodo para cuando sale el raton  en el panel de Buscar
     * @param evt
     */
    private void textBtBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtBuscarMouseExited
        botonBuscar.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtBuscarMouseExited
    
    /**
     * Metodo para la accion de clicar en el boton de borrar
     * @param evt
     */
    private void textBtBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtBorrarMouseClicked
        int n = JOptionPane.showConfirmDialog(
                this,
                "¿Estas seguro de querer borrar el alumno?",
                "Alumno borrado",
                JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.OK_OPTION) {
            try {
                gesAlu.buscar("", telefono);
                gesAlu.baja(telefono);
                cajaBusqueda.setText("");
                textoNombre.setText("");
                textoApellido.setText("");
                textoDireccion.setText("");
                textoTelefono.setText("");
                ArrayList<String> lista = new ArrayList();
                refrescar(lista);
                javax.swing.JOptionPane.showMessageDialog(this, "Borrado con exito", "BAJA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } catch (MisExceptions me) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "BAJA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_textBtBorrarMouseClicked

    /**
     * Metodo para cuando entra el raton en el panel de Borrar
     * @param evt
     */
    private void textBtBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtBorrarMouseEntered
        btBorrar.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtBorrarMouseEntered

    /**
     * Metodo para cuando sale el raton en el panel de Borrar
     * @param evt
     */
    private void textBtBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtBorrarMouseExited
        btBorrar.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtBorrarMouseExited

    /**
     * Metodo para el evento de clicar que recoje los parametros de las cajas para modificar los 
     * datos del alumno
     * @param evt
     */
    private void textBtModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtModificarMouseClicked
        this.nombre = textoNombre.getText().trim();
        this.apellido = textoApellido.getText().trim();
        String telNuevo = textoTelefono.getText().trim();
        this.direccion = textoDireccion.getText().trim();

        System.out.println(this.telefono);
        try {
            verif.hayAlgo(nombre);
            verif.tieneComa(nombre);
            verif.hayAlgo(apellido);
            verif.tieneComa(apellido);
            verif.hayAlgo(telNuevo);
            verif.nuveCaracteres(telNuevo);
            verif.soloNum(telNuevo);
            gesAlu.buscar("", telefono);
            verif.hayAlgo(direccion);
            verif.tieneComa(direccion);

            this.rs = gesAlu.buscar("", telefono);
            if (rs.next()) {
                int id = rs.getInt("id_alumno");
                gesAlu.modificar(nombre, apellido, telNuevo, direccion, id);
            }

            textoNombre.setText("");
            textoApellido.setText("");
            textoTelefono.setText("");
            textoDireccion.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Alumno modificado con exito", "ALTA", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
//            ex.printStackTrace();
        } catch (MisExceptions me) {
            System.out.println("Error: " + me);
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "ALTA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_textBtModificarMouseClicked

    /**
     * Metodo para cuando entra el raton en el panel de Buscar
     * @param evt
     */
    private void textBtModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtModificarMouseEntered
        btModificar.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtModificarMouseEntered

    /**
     * Metodo para cuando sale el raton en el panel de Buscar
     * @param evt
     */
    private void textBtModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtModificarMouseExited
        btModificar.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtModificarMouseExited

    /**
     * Metodo para cuando clicamos en la caja de busqueda que quite el mensaje que esta escrito
     * @param evt
     */
    private void cajaBusquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaBusquedaMousePressed
        if (cajaBusqueda.getText().equals("Introduce el nombre del Alumno")) {
            cajaBusqueda.setText("");
            cajaBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_cajaBusquedaMousePressed

    /**
     * Metodo para cuando clicamos dos veces en un elemento de la lista
     * @param evt
     */
    private void pListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pListaMouseClicked
        javax.swing.JList<String> list = (javax.swing.JList) evt.getSource();

        if (evt.getClickCount() == 2) {// Si detecta doble click(2 click)
            // Double-click detected
            int index = list.locationToIndex(evt.getPoint());//Extraemos la posicion del elemento seleccionado
            String item = list.getModel().getElementAt(index);
            //Extraemos el nombre
            String campos[] = item.split(",");
//            String camposAux[] = campos[1].split(",");
            String telefono = campos[2].trim();
            try {
                this.rs = gesAlu.buscar("", telefono);//Extraemos el empleado al que corresponde la posicion seleccionada
                if (this.rs.next()) {
                    textoNombre.setText(this.rs.getString("nombre"));
                    textoDireccion.setText(this.rs.getString("correo_electronico"));
                    textoApellido.setText(this.rs.getString("apellido"));
                    textoTelefono.setText(this.rs.getString("telefono"));
                    this.telefono = rs.getString("telefono");
                }
            } catch (SQLException ex) {
//                ex.printStackTrace();
            } catch (MisExceptions me) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + me, "BUSQUEDA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_pListaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonBuscar;
    private javax.swing.JPanel btBorrar;
    private javax.swing.JPanel btModificar;
    private javax.swing.JTextField cajaBusqueda;
    private javax.swing.JLabel etqApellido;
    private javax.swing.JLabel etqDireccion;
    private javax.swing.JLabel etqNombre;
    private javax.swing.JLabel etqTelefono;
    private javax.swing.JScrollPane listadoAlumnos;
    private javax.swing.JList<String> pLista;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JLabel textBtBorrar;
    private javax.swing.JLabel textBtBuscar;
    private javax.swing.JLabel textBtModificar;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
    private String nombre;
    private String apellido;
    private String direccion;
    private String telefono;
    private GestionAlumnos gesAlu;
    private Verificaciones verif = new Verificaciones();
    ResultSet rs;

}
