/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import AgendaAlumnosCursos.GestionAlumnos;
import AgendaAlumnosCursos.MisExceptions;
import AgendaAlumnosCursos.Verificaciones;

/**
 *
 * @author Iker Ruiz
 */
public class PanelAltaAlumnos extends javax.swing.JPanel {
        

    /**
     * Creates new form PanelTrabAlumnos
     */
    public PanelAltaAlumnos(GestionAlumnos gesAlu) {        
        initComponents();
        this.gesAlu = gesAlu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrabajo = new javax.swing.JPanel();
        etqNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etqApellido = new javax.swing.JLabel();
        textoApellido = new javax.swing.JTextField();
        etqDireccion = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        textoTelefono = new javax.swing.JTextField();
        etqTelefono = new javax.swing.JLabel();
        botonEntrar = new javax.swing.JPanel();
        textBtEntrar = new javax.swing.JLabel();

        panelTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        panelTrabajo.setPreferredSize(new java.awt.Dimension(0, 589));

        etqNombre.setBackground(new java.awt.Color(51, 51, 51));
        etqNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqNombre.setForeground(new java.awt.Color(51, 51, 51));
        etqNombre.setText("Nombre");

        textoNombre.setBackground(new java.awt.Color(204, 204, 204));
        textoNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoNombre.setForeground(new java.awt.Color(51, 51, 51));

        etqApellido.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqApellido.setForeground(new java.awt.Color(51, 51, 51));
        etqApellido.setText("Apellido");

        textoApellido.setBackground(new java.awt.Color(204, 204, 204));
        textoApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoApellido.setForeground(new java.awt.Color(51, 51, 51));

        etqDireccion.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqDireccion.setForeground(new java.awt.Color(51, 51, 51));
        etqDireccion.setText("Direccion ");

        textoDireccion.setBackground(new java.awt.Color(204, 204, 204));
        textoDireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoDireccion.setForeground(new java.awt.Color(51, 51, 51));

        textoTelefono.setBackground(new java.awt.Color(204, 204, 204));
        textoTelefono.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textoTelefono.setForeground(new java.awt.Color(51, 51, 51));

        etqTelefono.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        etqTelefono.setForeground(new java.awt.Color(51, 51, 51));
        etqTelefono.setText("Telefono");

        botonEntrar.setBackground(new java.awt.Color(78, 156, 204));

        textBtEntrar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        textBtEntrar.setForeground(new java.awt.Color(255, 255, 255));
        textBtEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBtEntrar.setText("Guardar");
        textBtEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        textBtEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textBtEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textBtEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textBtEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout botonEntrarLayout = new javax.swing.GroupLayout(botonEntrar);
        botonEntrar.setLayout(botonEntrarLayout);
        botonEntrarLayout.setHorizontalGroup(
            botonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textBtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonEntrarLayout.setVerticalGroup(
            botonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(textBtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqNombre)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqApellido)
                    .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqDireccion)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etqTelefono))
                .addContainerGap(665, Short.MAX_VALUE))
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(etqNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(etqApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(etqDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(etqTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(botonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo para cuando clicamos recoge los datos que hay en las cajas las compruba
     *  y pasa los datos a gestion de Alumnos
     * @param evt 
     */
    private void textBtEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtEntrarMouseClicked
       this.nombre = textoNombre.getText().trim();
       this.apellido = textoApellido.getText().trim();
       this.telefono = textoTelefono.getText().trim();
       this.direccion = textoDireccion.getText().trim();
       try{
           verif.hayAlgo(nombre);
           verif.tieneComa(nombre);
           verif.hayAlgo(apellido);
           verif.tieneComa(apellido);
           verif.hayAlgo(telefono);
           verif.hayAlgo(direccion);
           verif.tieneComa(direccion);
           verif.soloNum(telefono);
           verif.nuveCaracteres(telefono);
           gesAlu.alta(nombre, apellido, telefono, direccion);
            textoNombre.setText("");
            textoApellido.setText("");
            textoTelefono.setText("");
            textoDireccion.setText("");
           javax.swing.JOptionPane.showMessageDialog(this, "Alumno dado de alta con exito", "ALTA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
             
              
       }catch(MisExceptions me){
           System.out.println("Error: "+me);
            javax.swing.JOptionPane.showMessageDialog(this, "Error: "+me, "ALTA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
       }
        
        
    }//GEN-LAST:event_textBtEntrarMouseClicked

    /**
     * metodo para cambiar el color cuando pasa por encima el raton del boton  de registrar
     * @param evt 
     */
    private void textBtEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtEntrarMouseEntered
        botonEntrar.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_textBtEntrarMouseEntered

    /**
     * metodo para cambiar el color cuando sale del raton del boton de regisrar
     * @param evt 
     */
    private void textBtEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textBtEntrarMouseExited
        botonEntrar.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_textBtEntrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonEntrar;
    private javax.swing.JLabel etqApellido;
    private javax.swing.JLabel etqDireccion;
    private javax.swing.JLabel etqNombre;
    private javax.swing.JLabel etqTelefono;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JLabel textBtEntrar;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
    private String nombre;
    private String apellido;
    private String direccion;
    private String telefono;
    private GestionAlumnos gesAlu;
    private Verificaciones verif = new Verificaciones();


}
