/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import AgendaAlumnosCursos.GestionAlumnos;
import AgendaAlumnosCursos.VentaGestion;

/**
 *
 * @author Iker Ruiz
 */
public class SubMenuAlu extends javax.swing.JPanel {

    private VentaGestion vg;

    /**
     * Creates new form SubMenu
     */
    public SubMenuAlu(VentaGestion vg, GestionAlumnos gesAlu) {       
        initComponents();
         this.vg = vg;
         this.gesAlu = gesAlu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAltaAlumno = new javax.swing.JPanel();
        altaAlu = new javax.swing.JLabel();
        btGestAlu = new javax.swing.JPanel();
        gestAlu = new javax.swing.JLabel();
        btListAlu = new javax.swing.JPanel();
        listAlu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(49, 118, 187));
        setLayout(new java.awt.GridLayout(1, 4));

        btAltaAlumno.setBackground(new java.awt.Color(49, 118, 187));

        altaAlu.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        altaAlu.setForeground(new java.awt.Color(255, 255, 255));
        altaAlu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altaAlu.setText("Alta");
        altaAlu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altaAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaAluMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                altaAluMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                altaAluMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btAltaAlumnoLayout = new javax.swing.GroupLayout(btAltaAlumno);
        btAltaAlumno.setLayout(btAltaAlumnoLayout);
        btAltaAlumnoLayout.setHorizontalGroup(
            btAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altaAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btAltaAlumnoLayout.setVerticalGroup(
            btAltaAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altaAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btAltaAlumno);

        btGestAlu.setBackground(new java.awt.Color(49, 118, 187));

        gestAlu.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gestAlu.setForeground(new java.awt.Color(255, 255, 255));
        gestAlu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestAlu.setText("Gestion");
        gestAlu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gestAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestAluMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gestAluMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gestAluMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btGestAluLayout = new javax.swing.GroupLayout(btGestAlu);
        btGestAlu.setLayout(btGestAluLayout);
        btGestAluLayout.setHorizontalGroup(
            btGestAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btGestAluLayout.setVerticalGroup(
            btGestAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btGestAlu);

        btListAlu.setBackground(new java.awt.Color(49, 118, 187));

        listAlu.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        listAlu.setForeground(new java.awt.Color(255, 255, 255));
        listAlu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listAlu.setText("Listado");
        listAlu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listAluMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listAluMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listAluMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btListAluLayout = new javax.swing.GroupLayout(btListAlu);
        btListAlu.setLayout(btListAluLayout);
        btListAluLayout.setHorizontalGroup(
            btListAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btListAluLayout.setVerticalGroup(
            btListAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btListAlu);
    }// </editor-fold>//GEN-END:initComponents

    private void altaAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaAluMouseClicked
       vg.mostrarPanelTrabajo(new PanelAltaAlumnos(this.gesAlu));
       
       
    }//GEN-LAST:event_altaAluMouseClicked

    private void altaAluMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaAluMouseEntered
        btAltaAlumno.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_altaAluMouseEntered

    private void gestAluMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestAluMouseEntered
        btGestAlu.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_gestAluMouseEntered

    private void altaAluMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaAluMouseExited
        btAltaAlumno.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_altaAluMouseExited

    private void gestAluMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestAluMouseExited
        btGestAlu.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_gestAluMouseExited

    private void gestAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestAluMouseClicked
        vg.mostrarPanelTrabajo(new PanelGestionAlumno(this.gesAlu));
    }//GEN-LAST:event_gestAluMouseClicked

    private void listAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAluMouseClicked
      
        vg.mostrarPanelTrabajo(new PanelListadoAlumnos(this.gesAlu));
       
    }//GEN-LAST:event_listAluMouseClicked

    private void listAluMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAluMouseEntered
       btListAlu.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_listAluMouseEntered

    private void listAluMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listAluMouseExited
        btListAlu.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_listAluMouseExited
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altaAlu;
    private javax.swing.JPanel btAltaAlumno;
    private javax.swing.JPanel btGestAlu;
    private javax.swing.JPanel btListAlu;
    private javax.swing.JLabel gestAlu;
    private javax.swing.JLabel listAlu;
    // End of variables declaration//GEN-END:variables
    private GestionAlumnos gesAlu;
}
