/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import AgendaAlumnosCursos.GestionCursos;
import AgendaAlumnosCursos.VentaGestion;

/**
 *
 * @author Iker Ruiz
 */
public class SubMenuCurso extends javax.swing.JPanel {

    private VentaGestion vg;

    /**
     * Creates new form SubMenu
     */
    public SubMenuCurso(VentaGestion vg, GestionCursos gesCurso) {       
        initComponents();
         this.vg = vg;
         this.gesCurso = gesCurso;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAltaCurso = new javax.swing.JPanel();
        altaCurso = new javax.swing.JLabel();
        btGestCurso = new javax.swing.JPanel();
        gestCurso = new javax.swing.JLabel();
        btListaCurso = new javax.swing.JPanel();
        listCurso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(49, 118, 187));
        setLayout(new java.awt.GridLayout(1, 4));

        btAltaCurso.setBackground(new java.awt.Color(49, 118, 187));

        altaCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        altaCurso.setForeground(new java.awt.Color(255, 255, 255));
        altaCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altaCurso.setText("Alta");
        altaCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        altaCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                altaCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                altaCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                altaCursoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btAltaCursoLayout = new javax.swing.GroupLayout(btAltaCurso);
        btAltaCurso.setLayout(btAltaCursoLayout);
        btAltaCursoLayout.setHorizontalGroup(
            btAltaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altaCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btAltaCursoLayout.setVerticalGroup(
            btAltaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(altaCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btAltaCurso);

        btGestCurso.setBackground(new java.awt.Color(49, 118, 187));

        gestCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        gestCurso.setForeground(new java.awt.Color(255, 255, 255));
        gestCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gestCurso.setText("Gestion");
        gestCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gestCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gestCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gestCursoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btGestCursoLayout = new javax.swing.GroupLayout(btGestCurso);
        btGestCurso.setLayout(btGestCursoLayout);
        btGestCursoLayout.setHorizontalGroup(
            btGestCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btGestCursoLayout.setVerticalGroup(
            btGestCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gestCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btGestCurso);

        btListaCurso.setBackground(new java.awt.Color(49, 118, 187));

        listCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        listCurso.setForeground(new java.awt.Color(255, 255, 255));
        listCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listCurso.setText("Listado");
        listCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listCursoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btListaCursoLayout = new javax.swing.GroupLayout(btListaCurso);
        btListaCurso.setLayout(btListaCursoLayout);
        btListaCursoLayout.setHorizontalGroup(
            btListaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btListaCursoLayout.setVerticalGroup(
            btListaCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btListaCurso);
    }// </editor-fold>//GEN-END:initComponents

    private void altaCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaCursoMouseClicked
        vg.mostrarPanelTrabajo(new PanelAltaCursos(this.gesCurso));
    }//GEN-LAST:event_altaCursoMouseClicked

    private void altaCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaCursoMouseEntered
        btAltaCurso.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_altaCursoMouseEntered

    private void gestCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestCursoMouseEntered
        btGestCurso.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_gestCursoMouseEntered

    private void altaCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_altaCursoMouseExited
        btAltaCurso.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_altaCursoMouseExited

    private void gestCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestCursoMouseExited
        btGestCurso.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_gestCursoMouseExited

    private void gestCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestCursoMouseClicked
         vg.mostrarPanelTrabajo(new PanelGestionCurso(this.gesCurso));
    }//GEN-LAST:event_gestCursoMouseClicked

    private void listCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCursoMouseClicked
         vg.mostrarPanelTrabajo(new PanelListadoCursos(this.gesCurso));
    }//GEN-LAST:event_listCursoMouseClicked

    private void listCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCursoMouseEntered
       btListaCurso.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_listCursoMouseEntered

    private void listCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCursoMouseExited
        btListaCurso.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_listCursoMouseExited
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altaCurso;
    private javax.swing.JPanel btAltaCurso;
    private javax.swing.JPanel btGestCurso;
    private javax.swing.JPanel btListaCurso;
    private javax.swing.JLabel gestCurso;
    private javax.swing.JLabel listCurso;
    // End of variables declaration//GEN-END:variables
    private GestionCursos gesCurso;
}
