/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import java.awt.Color;
import AgendaAlumnosCursos.GestionInscripciones;
import AgendaAlumnosCursos.VentaGestion;

/**
 *
 * @author Iker Ruiz
 */
public class SubMenuMat extends javax.swing.JPanel {

    private VentaGestion vg;

    /**
     * Creates new form SubMenu
     */
    public SubMenuMat(VentaGestion vg, GestionInscripciones gesInsc) {
        this.vg = vg;
        initComponents();
        this.gesInsc = gesInsc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMat = new javax.swing.JPanel();
        mat = new javax.swing.JLabel();
        btInfoCurso = new javax.swing.JPanel();
        infoCurso = new javax.swing.JLabel();
        btInfoAlu = new javax.swing.JPanel();
        infoAlu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(49, 118, 187));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 4));

        btMat.setBackground(new java.awt.Color(49, 118, 187));

        mat.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        mat.setForeground(new java.awt.Color(255, 255, 255));
        mat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mat.setText("Matricular");
        mat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                matMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                matMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btMatLayout = new javax.swing.GroupLayout(btMat);
        btMat.setLayout(btMatLayout);
        btMatLayout.setHorizontalGroup(
            btMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mat, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btMatLayout.setVerticalGroup(
            btMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mat, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btMat);

        btInfoCurso.setBackground(new java.awt.Color(49, 118, 187));

        infoCurso.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        infoCurso.setForeground(new java.awt.Color(255, 255, 255));
        infoCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoCurso.setText("Info. Cursos");
        infoCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoCursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoCursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoCursoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btInfoCursoLayout = new javax.swing.GroupLayout(btInfoCurso);
        btInfoCurso.setLayout(btInfoCursoLayout);
        btInfoCursoLayout.setHorizontalGroup(
            btInfoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btInfoCursoLayout.setVerticalGroup(
            btInfoCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btInfoCurso);

        btInfoAlu.setBackground(new java.awt.Color(49, 118, 187));

        infoAlu.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        infoAlu.setForeground(new java.awt.Color(255, 255, 255));
        infoAlu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoAlu.setText("Info.Alumnos");
        infoAlu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoAlu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoAluMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoAluMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoAluMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btInfoAluLayout = new javax.swing.GroupLayout(btInfoAlu);
        btInfoAlu.setLayout(btInfoAluLayout);
        btInfoAluLayout.setHorizontalGroup(
            btInfoAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoAlu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        btInfoAluLayout.setVerticalGroup(
            btInfoAluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        add(btInfoAlu);
    }// </editor-fold>//GEN-END:initComponents

    private void matMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matMouseClicked
        vg.mostrarPanelTrabajo(new PanelMatricular(gesInsc));
    }//GEN-LAST:event_matMouseClicked

    private void matMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matMouseEntered
        btMat.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_matMouseEntered

    private void infoCursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoCursoMouseEntered
        btInfoCurso.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_infoCursoMouseEntered

    private void infoAluMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoAluMouseEntered
        btInfoAlu.setBackground(new Color(78, 156, 204));
    }//GEN-LAST:event_infoAluMouseEntered

    private void matMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matMouseExited
        btMat.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_matMouseExited

    private void infoCursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoCursoMouseExited
        btInfoCurso.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_infoCursoMouseExited

    private void infoAluMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoAluMouseExited
        btInfoAlu.setBackground(new Color(49, 118, 187));
    }//GEN-LAST:event_infoAluMouseExited

    private void infoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoCursoMouseClicked
         vg.mostrarPanelTrabajo(new PanelInfoCursos(gesInsc));
    }//GEN-LAST:event_infoCursoMouseClicked

    private void infoAluMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoAluMouseClicked
        vg.mostrarPanelTrabajo(new PanelInfoAlumnos(gesInsc));
    }//GEN-LAST:event_infoAluMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btInfoAlu;
    private javax.swing.JPanel btInfoCurso;
    private javax.swing.JPanel btMat;
    private javax.swing.JLabel infoAlu;
    private javax.swing.JLabel infoCurso;
    private javax.swing.JLabel mat;
    // End of variables declaration//GEN-END:variables
    GestionInscripciones gesInsc;
}
